// <auto-generated />
namespace Bookland.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1to1UserProfileCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1to1UserProfileCart));
        
        string IMigrationMetadata.Id
        {
            get { return "201311270021256_1-to-1UserProfileCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
